language: python
python:
  # Disable 2.6 as `unit2 discover` doesn't work with another Python package
  # installed from source with an identically named test directory
  # http://parenchym.com/pymblog/python-unittest-discover-quirks.html
  # - "2.6"
  - "2.7"
# ROOT versions to test
env:
  - ROOT_VERSION=5.34.19
  - ROOT_VERSION=6.00.02
# Install GCC 4.8, required for ROOT 6
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get -y install gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
install:
  # Install ROOT using pre-built tarballs
  # https://github.com/alexpearce/travis-ci-root-builds
  - wget --no-check-certificate https://dl.dropboxusercontent.com/u/37461/travis-ci-root-builds/ROOT-${ROOT_VERSION}_Python-${TRAVIS_PYTHON_VERSION}.tar.gz
  - tar xzf ROOT-${ROOT_VERSION}_Python-${TRAVIS_PYTHON_VERSION}.tar.gz
  - mv ROOT-${ROOT_VERSION}_Python-${TRAVIS_PYTHON_VERSION}/root root
  - source root/bin/thisroot.sh
  # Install production and test dependencies, then create some dummy data
  - pip install -r requirements.txt
  - pip install unittest2 flake8
  - cd monitoring_app/static/files && python generate_histograms.py && cd ../../..
script:
  - flake8 monitoring_app
  - python -m unittest2 discover
